Game5.0: Game5.0.o Subtask1.o Subtask2.o Subtask3.o Subtask4.o Subtask5.o Subtask6.o RSA.o
	gcc -g -o Game5.0.exe Game5.0.o Subtask1.o Subtask2.o Subtask3.o Subtask4.o Subtask5.o Subtask6.o RSA.o
Subtask1.o: Subtask1.c Subtask1.h
	gcc -g -c Subtask1.c
Subtask2.o: Subtask2.c Subtask2.h
	gcc -g -c Subtask2.c
Subtask3.o: Subtask3.c Subtask3.h
	gcc -g -c Subtask3.c
Subtask4.o: Subtask4.c Subtask4.h
	gcc -g -c Subtask4.c
Subtask5.o: Subtask5.c Subtask5.h
	gcc -g -c Subtask5.c
Subtask6.o: Subtask6.c Subtask6.h
	gcc -g -c Subtask6.c
RSA.o: RSA.c RSA.h
	gcc -g -c RSA.c
Game5.0.o: Game5.0.c
	gcc -g -c Game5.0.c