frame: frame.o Subtask1.o Subtask2.o Subtask3.o
	gcc -g -o frame.exe frame.o Subtask1.o Subtask2.o Subtask3.o
Subtask1.o: Subtask1.c Subtask1.h
	gcc -g -c Subtask1.c
Subtask2.o: Subtask2.c Subtask2.h
	gcc -g -c Subtask2.c
Subtask3.o: Subtask3.c Subtask3.h
	gcc -g -c Subtask3.c
frame.o: frame.c
	gcc -g -c frame.c