frame: frame3.0.o Subtask1.o Subtask2.o Subtask3.o Subtask5.o
	gcc -g -o frame3.0.exe frame3.0.o Subtask1.o Subtask2.o Subtask3.o Subtask5.o
Subtask1.o: Subtask1.c Subtask1.h
	gcc -g -c Subtask1.c
Subtask2.o: Subtask2.c Subtask2.h
	gcc -g -c Subtask2.c
Subtask3.o: Subtask3.c Subtask3.h
	gcc -g -c Subtask3.c
Subtask5.o: Subtask5.c Subtask5.h
	gcc -g -c Subtask5.c
frame3.0.o: frame3.0.c
	gcc -g -c frame3.0.c